import { Locale } from './locales';

// Type for page metadata
export interface PageMetadata {
  title: string;
  description: string;
  keywords?: string[];
}

// Metadata for homepage by locale
export const homeMetadata: Record<Locale, PageMetadata> = {
  en: {
    title: 'Coral Boats Mallorca - Premium Boat Tours in Bay of Alcudia | Snorkeling & Private Charters',
    description: 'Experience the magic of Mallorca with Coral Boats premium boat tours in the Bay of Alcudia. Choose from morning, afternoon, or sunset tours featuring snorkeling, paddle boarding, authentic Mallorcan tapas, and unlimited drinks. Book your unforgettable Mediterranean adventure aboard our classic 1968 boat, Amayna II. Private charters available for weddings, corporate events, and special celebrations.',
    keywords: [
      'Mallorca boat tours',
      'Bay of Alcudia boat trips',
      'Alcudia boat excursions',
      'snorkeling Mallorca',
      'Mallorca sunset cruise',
      'private boat charter Mallorca',
      'boat tour Port Alcudia',
      'Mediterranean boat tours',
      'Mallorca hidden coves',
      'paddle boarding Mallorca',
      'Mallorcan tapas boat tour',
      'boat rental Mallorca',
      'sunset boat tour Alcudia',
      'family boat tour Mallorca',
      'romantic boat cruise Mallorca',
    ],
  },
  es: {
    title: 'Coral Boats Mallorca - Tours en Barco Premium en la Bahía de Alcudia | Snorkel y Charters Privados',
    description: 'Experimenta la magia de Mallorca con los tours en barco premium de Coral Boats en la Bahía de Alcudia. Elige entre tours de mañana, tarde o atardecer con snorkel, paddle surf, tapas mallorquinas auténticas y bebidas ilimitadas. Reserva tu aventura mediterránea inolvidable a bordo de nuestro barco clásico de 1968, Amayna II. Charters privados disponibles para bodas, eventos corporativos y celebraciones especiales.',
    keywords: [
      'tours en barco Mallorca',
      'excursiones en barco Bahía de Alcudia',
      'excursiones barco Alcudia',
      'snorkel Mallorca',
      'crucero atardecer Mallorca',
      'charter privado barco Mallorca',
      'tour barco Puerto Alcudia',
      'tours barco Mediterráneo',
      'calas escondidas Mallorca',
      'paddle surf Mallorca',
      'tour barco tapas mallorquinas',
      'alquiler barco Mallorca',
      'tour atardecer Alcudia',
      'tour barco familiar Mallorca',
      'crucero romántico Mallorca',
    ],
  },
  de: {
    title: 'Coral Boats Mallorca - Premium Bootstouren in der Bucht von Alcudia | Schnorcheln & Private Charter',
    description: 'Erleben Sie die Magie Mallorcas mit den Premium-Bootstouren von Coral Boats in der Bucht von Alcudia. Wählen Sie zwischen Morgen-, Nachmittags- oder Sonnenuntergangstouren mit Schnorcheln, Paddle-Boarding, authentischen mallorquinischen Tapas und unbegrenzten Getränken. Buchen Sie Ihr unvergessliches Mittelmeer-Abenteuer an Bord unseres klassischen Bootes von 1968, Amayna II. Private Charter für Hochzeiten, Firmenevents und besondere Feiern verfügbar.',
    keywords: [
      'Mallorca Bootstouren',
      'Bucht von Alcudia Bootsausflüge',
      'Alcudia Bootsexkursionen',
      'Schnorcheln Mallorca',
      'Mallorca Sonnenuntergangsfahrt',
      'privater Bootscharter Mallorca',
      'Bootstour Port Alcudia',
      'Mittelmeer Bootstouren',
      'versteckte Buchten Mallorca',
      'Paddle-Boarding Mallorca',
      'Bootstour mallorquinische Tapas',
      'Bootverleih Mallorca',
      'Sonnenuntergang Bootstour Alcudia',
      'Familien Bootstour Mallorca',
      'romantische Bootsfahrt Mallorca',
    ],
  },
  fr: {
    title: 'Coral Boats Majorque - Excursions en Bateau Premium dans la Baie d\'Alcudia | Snorkeling & Charters Privés',
    description: 'Découvrez la magie de Majorque avec les excursions en bateau premium de Coral Boats dans la Baie d\'Alcudia. Choisissez parmi des tours matinaux, d\'après-midi ou au coucher du soleil avec snorkeling, paddle board, tapas majorquines authentiques et boissons illimitées. Réservez votre aventure méditerranéenne inoubliable à bord de notre bateau classique de 1968, Amayna II. Charters privés disponibles pour mariages, événements d\'entreprise et célébrations spéciales.',
    keywords: [
      'excursions bateau Majorque',
      'sorties bateau Baie d\'Alcudia',
      'excursions bateau Alcudia',
      'snorkeling Majorque',
      'croisière coucher de soleil Majorque',
      'charter privé bateau Majorque',
      'tour bateau Port d\'Alcudia',
      'excursions bateau Méditerranée',
      'criques cachées Majorque',
      'paddle board Majorque',
      'tour bateau tapas majorquines',
      'location bateau Majorque',
      'tour coucher de soleil Alcudia',
      'tour bateau familial Majorque',
      'croisière romantique Majorque',
    ],
  },
  it: {
    title: 'Coral Boats Maiorca - Tour in Barca Premium nella Baia di Alcudia | Snorkeling e Charter Privati',
    description: 'Vivi la magia di Maiorca con i tour in barca premium di Coral Boats nella Baia di Alcudia. Scegli tra tour mattutini, pomeridiani o al tramonto con snorkeling, paddle boarding, autentiche tapas maiorchine e bevande illimitate. Prenota la tua indimenticabile avventura mediterranea a bordo della nostra barca classica del 1968, Amayna II. Charter privati disponibili per matrimoni, eventi aziendali e celebrazioni speciali.',
    keywords: [
      'tour in barca Maiorca',
      'gite in barca Baia di Alcudia',
      'escursioni in barca Alcudia',
      'snorkeling Maiorca',
      'crociera al tramonto Maiorca',
      'charter privato barca Maiorca',
      'tour barca Porto di Alcudia',
      'tour in barca Mediterraneo',
      'calette nascoste Maiorca',
      'paddle boarding Maiorca',
      'tour barca tapas maiorchine',
      'noleggio barca Maiorca',
      'tour tramonto Alcudia',
      'tour barca famigliare Maiorca',
      'crociera romantica Maiorca',
    ],
  },
  ca: {
    title: 'Coral Boats Mallorca - Tours en Vaixell Premium a la Badia d\'Alcúdia | Snorkel i Charters Privats',
    description: 'Experimenta la màgia de Mallorca amb els tours en vaixell premium de Coral Boats a la Badia d\'Alcúdia. Tria entre tours de matí, tarda o posta de sol amb snorkel, paddle surf, tapes mallorquines autèntiques i begudes il·limitades. Reserva la teva aventura mediterrània inoblidable a bord del nostre vaixell clàssic de 1968, Amayna II. Charters privats disponibles per a casaments, events corporatius i celebracions especials.',
    keywords: [
      'tours en vaixell Mallorca',
      'excursions vaixell Badia d\'Alcúdia',
      'excursions vaixell Alcúdia',
      'snorkel Mallorca',
      'creuer posta de sol Mallorca',
      'charter privat vaixell Mallorca',
      'tour vaixell Port d\'Alcúdia',
      'tours vaixell Mediterrani',
      'cales amagades Mallorca',
      'paddle surf Mallorca',
      'tour vaixell tapes mallorquines',
      'lloguer vaixell Mallorca',
      'tour posta de sol Alcúdia',
      'tour vaixell familiar Mallorca',
      'creuer romàntic Mallorca',
    ],
  },
};
