import { Locale } from './locales';

// Type for page metadata
export interface PageMetadata {
  title: string;
  description: string;
  keywords?: string[];
}

// Metadata for homepage by locale
export const homeMetadata: Record<Locale, PageMetadata> = {
  en: {
    title: 'Boat Trips in Alcudia | Morning & Sunset Tours in Mallorca',
    description: 'Discover the best boat trips in Alcudia. Enjoy morning or sunset tours in small groups with snorkeling, paddleboarding, and beautiful coastal views. Private charters available.',
    keywords: [
      'Mallorca boat tours',
      'Bay of Alcudia boat trips',
      'Alcudia boat excursions',
      'snorkeling Mallorca',
      'Mallorca sunset cruise',
      'private boat charter Mallorca',
      'boat tour Port Alcudia',
      'Mediterranean boat tours',
      'Mallorca hidden coves',
      'paddle boarding Mallorca',
      'Mallorcan tapas boat tour',
      'boat rental Mallorca',
      'sunset boat tour Alcudia',
      'family boat tour Mallorca',
      'romantic boat cruise Mallorca',
    ],
  },
  es: {
    title: 'Excursiones en Barco en Alcudia | Tours de Mañana y Atardecer en Mallorca',
    description: 'Descubre las mejores excursiones en barco en Alcudia. Disfruta tours de mañana o atardecer en grupos reducidos con snorkel, paddleboard y vistas costeras. Charters privados disponibles.',
    keywords: [
      'tours en barco Mallorca',
      'excursiones en barco Bahía de Alcudia',
      'excursiones barco Alcudia',
      'snorkel Mallorca',
      'crucero atardecer Mallorca',
      'charter privado barco Mallorca',
      'tour barco Puerto Alcudia',
      'tours barco Mediterráneo',
      'calas escondidas Mallorca',
      'paddle surf Mallorca',
      'tour barco tapas mallorquinas',
      'alquiler barco Mallorca',
      'tour atardecer Alcudia',
      'tour barco familiar Mallorca',
      'crucero romántico Mallorca',
    ],
  },
  de: {
    title: 'Bootstouren in Alcudia | Morgen- & Sonnenuntergangsfahrten auf Mallorca',
    description: 'Entdecke die besten Bootstouren in Alcudia. Genieße Morgen- oder Sonnenuntergangsfahrten in kleinen Gruppen mit Schnorcheln, Paddleboarding und wunderschönen Küstenblicken. Private Charters verfügbar.',
    keywords: [
      'Mallorca Bootstouren',
      'Bucht von Alcudia Bootsausflüge',
      'Alcudia Bootsexkursionen',
      'Schnorcheln Mallorca',
      'Mallorca Sonnenuntergangsfahrt',
      'privater Bootscharter Mallorca',
      'Bootstour Port Alcudia',
      'Mittelmeer Bootstouren',
      'versteckte Buchten Mallorca',
      'Paddle-Boarding Mallorca',
      'Bootstour mallorquinische Tapas',
      'Bootverleih Mallorca',
      'Sonnenuntergang Bootstour Alcudia',
      'Familien Bootstour Mallorca',
      'romantische Bootsfahrt Mallorca',
    ],
  },
  fr: {
    title: 'Excursions en Bateau à Alcudia | Tours du Matin et du Coucher du Soleil à Majorque',
    description: 'Découvrez les meilleures excursions en bateau à Alcudia. Profitez de tours matinaux ou au coucher du soleil en petits groupes avec snorkeling, paddleboard et magnifiques vues côtières. Charters privés disponibles.',
    keywords: [
      'excursions bateau Majorque',
      'sorties bateau Baie d\'Alcudia',
      'excursions bateau Alcudia',
      'snorkeling Majorque',
      'croisière coucher de soleil Majorque',
      'charter privé bateau Majorque',
      'tour bateau Port d\'Alcudia',
      'excursions bateau Méditerranée',
      'criques cachées Majorque',
      'paddle board Majorque',
      'tour bateau tapas majorquines',
      'location bateau Majorque',
      'tour coucher de soleil Alcudia',
      'tour bateau familial Majorque',
      'croisière romantique Majorque',
    ],
  },
  it: {
    title: 'Gite in Barca ad Alcudia | Tour del Mattino e del Tramonto a Maiorca',
    description: 'Scopri le migliori gite in barca ad Alcudia. Goditi tour mattutini o al tramonto in piccoli gruppi con snorkeling, paddleboard e splendide viste costiere. Disponibili charter privati.',
    keywords: [
      'tour in barca Maiorca',
      'gite in barca Baia di Alcudia',
      'escursioni in barca Alcudia',
      'snorkeling Maiorca',
      'crociera al tramonto Maiorca',
      'charter privato barca Maiorca',
      'tour barca Porto di Alcudia',
      'tour in barca Mediterraneo',
      'calette nascoste Maiorca',
      'paddle boarding Maiorca',
      'tour barca tapas maiorchine',
      'noleggio barca Maiorca',
      'tour tramonto Alcudia',
      'tour barca famigliare Maiorca',
      'crociera romantica Maiorca',
    ],
  },
  ca: {
    title: 'Excursions en Vaixell a Alcúdia | Tours de Matí i Capvespre a Mallorca',
    description: 'Descobreix les millors excursions en barco a Alcúdia. Gaudeix de tours de matí o capvespre en grups reduïts amb snorkel, paddleboard i vistes costaneres. Charters privats disponibles.',
    keywords: [
      'tours en vaixell Mallorca',
      'excursions vaixell Badia d\'Alcúdia',
      'excursions vaixell Alcúdia',
      'snorkel Mallorca',
      'creuer posta de sol Mallorca',
      'charter privat vaixell Mallorca',
      'tour vaixell Port d\'Alcúdia',
      'tours vaixell Mediterrani',
      'cales amagades Mallorca',
      'paddle surf Mallorca',
      'tour vaixell tapes mallorquines',
      'lloguer vaixell Mallorca',
      'tour posta de sol Alcúdia',
      'tour vaixell familiar Mallorca',
      'creuer romàntic Mallorca',
    ],
  },
};
